const categories=[
['טלפונים','📱',['Apple','Samsung','Google','Xiaomi','OnePlus','Motorola','Nokia','Huawei','Sony','Nothing']],
['טאבלטים','▣',['Apple','Samsung','Lenovo','Microsoft','Huawei','Xiaomi','Amazon','Google','Asus','TCL']],
['מחשבים ניידים','▰',['Apple','Dell','HP','Lenovo','Asus','Acer','Microsoft','MSI','Razer','Samsung']],
['מחשבים נייחים','▥',['Dell','HP','Lenovo','Asus','Acer','MSI','Intel','Apple','Gigabyte','Custom PC']],
['קונסולות','🎮',['Sony','Microsoft','Nintendo','Valve','Asus','Lenovo','Sega','Nvidia','Atari','Retroid']],
['טלוויזיות','▭',['Samsung','LG','Sony','TCL','Hisense','Philips','Panasonic','Xiaomi','Sharp','Vizio']],
['מסכים','▱',['Dell','LG','Samsung','Asus','Acer','BenQ','MSI','AOC','ViewSonic','HP']],
['מדפסות','▤',['HP','Canon','Epson','Brother','Samsung','Xerox','Lexmark','Ricoh','Kyocera','Pantum']],
['ראוטרים ורשת','⌁',['TP-Link','Asus','Netgear','D-Link','Linksys','Ubiquiti','Eero','Google','Huawei','MikroTik']],
['שעונים חכמים','◉',['Apple','Samsung','Google','Garmin','Fitbit','Huawei','Amazfit','Xiaomi','OnePlus','Fossil']],
['אוזניות ושמע','♫',['Apple','Sony','Bose','Samsung','JBL','Sennheiser','Beats','Anker','Logitech','SteelSeries']],
['מצלמות','◌',['Canon','Nikon','Sony','Fujifilm','Panasonic','GoPro','DJI','Olympus','Leica','Insta360']],
['בית חכם','⌂',['Google','Amazon','Apple','Samsung','Philips Hue','Ring','Eufy','Aqara','Xiaomi','Sonos']],
['סטרימרים','▶',['Apple','Google','Amazon','Roku','Nvidia','Xiaomi','Chromecast','Homatics','Dune','Formuler']],
['רחפנים','✣',['DJI','Autel','Parrot','Skydio','Ryze','Holy Stone','Potensic','Yuneec','Fimi','Hubsan']],
['אביזרי מחשב','⌨',['Logitech','Razer','Corsair','SteelSeries','HyperX','Keychron','Microsoft','Apple','Wacom','Elgato']]
];
const issues=[
['לא נדלק','קל'],['לא נטען','קל'],['נכבה לבד','בינוני'],['מתחמם','בינוני'],['איטי מאוד','קל'],['קופא או נתקע','קל'],['מסך שחור','בינוני'],['מסך מהבהב','בינוני'],['אין תמונה','בינוני'],['אין קול','קל'],['Wi-Fi לא מתחבר','קל'],['Bluetooth לא עובד','קל'],['USB לא מזוהה','בינוני'],['עדכון נכשל','בינוני'],['איפוס להגדרות יצרן','קל'],['גיבוי מלא','קל'],['שחזור מגיבוי','בינוני'],['התקנה מחדש של מערכת הפעלה','מתקדם'],['Recovery לא עולה','מתקדם'],['Boot loop','בינוני'],['שכחתי קוד נעילה','בינוני'],['אחסון מלא','קל'],['סוללה נגמרת מהר','קל'],['החלפת סוללה','מתקדם'],['החלפת מסך','מתקדם'],['החלפת שקע טעינה','מתקדם'],['ניקוי פנימי','בינוני'],['נזק נוזלים — בדיקה ראשונית','בינוני'],['מצלמה לא עובדת','בינוני'],['מיקרופון לא עובד','בינוני'],['רמקול חלש','קל'],['כפתורים לא מגיבים','בינוני'],['לא מזוהה במחשב','בינוני'],['דרייבר חסר','קל'],['BIOS/UEFI לא עולה','מתקדם'],['איפוס BIOS/UEFI','מתקדם'],['SSD לא מזוהה','מתקדם'],['דיסק מלא','קל'],['שגיאת Boot','מתקדם'],['מערכת קורסת','בינוני'],['אפליקציות קורסות','קל'],['חיבור HDMI לא עובד','בינוני'],['חיבור DisplayPort לא עובד','בינוני'],['רשת איטית','קל'],['ניתוקים ברשת','קל'],['Factory reset','קל'],['עדכון Firmware','בינוני'],['שחזור Firmware','מתקדם'],['זיהוי נזק פיזי','בינוני'],['בדיקת ספק כוח','מתקדם'],['מאוורר רועש','בינוני'],['ניקוי אבק','בינוני'],['החלפת משחה תרמית','מתקדם'],['טמפרטורה גבוהה','בינוני'],['אין גישה לאינטרנט','קל'],['DNS לא עובד','קל'],['איפוס רשת','קל'],['איפוס סיסמה','קל'],['שחזור קבצים','מתקדם'],['העברת נתונים למכשיר חדש','קל'],['הגדרת מכשיר חדש','קל'],['התקנת דרייברים','קל'],['יצירת USB אתחול','בינוני'],['Dual Boot','מתקדם'],['Secure Boot בעייתי','מתקדם'],['TPM לא מזוהה','מתקדם'],['מצב בטוח / Safe Mode','קל'],['בדיקת אחריות לפני פירוק','קל'],['אבחון מלא לפני תיקון','בינוני'],['תחזוקה מונעת שנתית','קל']
];
const series=['Standard','Plus','Pro','Max','Air','Mini'];
let activeCat=''; let currentPage=1; const pageSize=12;
const count=categories.length*10*series.length*17*issues.length;
document.getElementById('catalogCount').innerHTML=count.toLocaleString('he-IL')+'<small>+</small>';
for(let y=2026;y>=2010;y--){year.insertAdjacentHTML('beforeend',`<option>${y}</option>`)}
function renderSide(){side.innerHTML='<h3>קטגוריות</h3>'+categories.map((c,i)=>`<button class="${activeCat===c[0]?'active':''}" onclick="pickCat('${c[0]}')"><span>${c[0]}</span><span class="n">${(10*6*17*issues.length).toLocaleString()}</span></button>`).join('')+'<hr><button onclick="pickCat(\'\')"><span>כל המכשירים</span><span class="n">'+count.toLocaleString()+'</span></button>'}
function renderCats(){cats.innerHTML=categories.map(c=>`<button class="cat" onclick="pickCat('${c[0]}')"><div class="ico">${c[1]}</div><b>${c[0]}</b><span>${(10*6*17*issues.length).toLocaleString()} מדריכים זמינים</span></button>`).join('')}
function pickCat(name){activeCat=name;currentPage=1;renderSide();searchGuides();document.getElementById('guides').scrollIntoView({behavior:'smooth'})}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)}
function generateMatches(q,yr,diff){const words=q.toLowerCase().trim().split(/\s+/).filter(Boolean);const matches=[];const catsToUse=activeCat?categories.filter(c=>c[0]===activeCat):categories;for(const c of catsToUse){for(const brand of c[2]){for(const s of series){for(let y=2026;y>=2010;y--){if(yr&&String(y)!==yr)continue;for(const [issue,d] of issues){if(diff&&d!==diff)continue;const title=`${brand} ${s} ${y} — ${issue}`;const hay=(title+' '+c[0]+' '+brand+' '+issue).toLowerCase();if(words.length&&!words.every(w=>hay.includes(w)))continue;matches.push({cat:c[0],brand,series:s,year:y,issue,diff:d,title,icon:c[1]});if(matches.length>=160)return matches}}}}}return matches}
function fallbackMatches(q,yr,diff){const words=q.toLowerCase().trim().split(/\s+/).filter(Boolean);const scored=[];for(const c of (activeCat?categories.filter(x=>x[0]===activeCat):categories)){for(const brand of c[2]){for(const [issue,d] of issues){if(diff&&d!==diff)continue;let text=(brand+' '+c[0]+' '+issue).toLowerCase();let score=words.reduce((n,w)=>n+(text.includes(w)?1:0),0);if(!words.length)score=1;if(score){let y=yr?+yr:2026-(hash(brand+issue)%17);let s=series[hash(issue+brand)%series.length];scored.push({cat:c[0],brand,series:s,year:y,issue,diff:d,title:`${brand} ${s} ${y} — ${issue}`,icon:c[1],score})}}}}return scored.sort((a,b)=>b.score-a.score).slice(0,120)}
function searchGuides(){const qv=q.value.trim(),yv=year.value,dv=difficulty.value;currentPage=1;let arr=generateMatches(qv,yv,dv);if(!arr.length&&qv)arr=fallbackMatches(qv,yv,dv);window.lastMatches=arr;resultTitle.textContent=qv?`תוצאות עבור “${qv}”`:(activeCat?activeCat:'מדריכים אחרונים');resultSub.textContent=`${arr.length?arr.length.toLocaleString():0} תוצאות מוצגות מתוך קטלוג של ${count.toLocaleString()} וריאציות`;renderResults()}
function renderResults(){const arr=window.lastMatches||[];const start=(currentPage-1)*pageSize,items=arr.slice(start,start+pageSize);results.innerHTML=items.length?items.map((g,i)=>`<article class="guide" onclick="openGuide(${start+i})"><div class="thumb">${g.icon}</div><div><h3>${g.title}</h3><p>${g.cat} · ${g.brand} · שנת ${g.year} · מדריך אבחון ותיקון שלב אחר שלב</p></div><div class="meta"><b>${g.diff}</b><span>${guideTime(g.diff)}</span><br><span class="badge">פתח מדריך ←</span></div></article>`).join(''):'<div class="empty">לא נמצאה התאמה מדויקת. נסה לחפש רק יצרן, סוג תקלה או מערכת הפעלה.</div>';const pages=Math.ceil(arr.length/pageSize);pager.innerHTML=pages>1?Array.from({length:Math.min(pages,6)},(_,i)=>`<button class="${currentPage===i+1?'active':''}" onclick="goPage(${i+1})">${i+1}</button>`).join(''):''}
function goPage(p){currentPage=p;renderResults();guides.scrollIntoView({behavior:'smooth'})}
function guideTime(d){return d==='קל'?'10–25 דקות':d==='בינוני'?'25–60 דקות':'45–120 דקות'}
function stepsFor(g){const common=[['תעד את התקלה','צלם הודעות שגיאה, רשום מה קרה לפני התקלה ובדוק אם היא חוזרת לאחר הפעלה מחדש.'],['נתק ציוד חיצוני','הסר אביזרים שאינם חיוניים ובדוק את המכשיר במצב בסיסי.'],['בצע בדיקה ממוקדת',`בצע את הבדיקה הרלוונטית לבעיה “${g.issue}”. אל תפרק חלקים לפני ששללת בעיית תוכנה, מתח, כבל או הגדרה.`],['בדוק לאחר השינוי','הפעל מחדש ובדוק את אותה פעולה שגרמה לתקלה. אם הבעיה נעלמה, החזר אביזרים אחד־אחד.'],['אם הבעיה נשארה','עצור לפני פעולה שעלולה למחוק נתונים או לפגוע בחומרה. גבה מידע ובדוק מדריך שירות רשמי לדגם המדויק.']];if(g.issue.includes('התקנה מחדש')||g.issue.includes('USB אתחול'))return [['גבה את המידע','שמור קבצים, קודי שחזור ומפתחות הצפנה לפני מחיקה או שינוי מחיצות.'],['הורד מקור רשמי','השתמש בקובץ ההתקנה או כלי יצירת המדיה הרשמי של ספק מערכת ההפעלה המתאימה למכשיר.'],['צור מדיית אתחול','צור USB אתחול במחשב תקין. ודא שהכונן הנבחר נכון כי הוא יימחק.'],['פתח את תפריט האתחול','הפעל Boot Menu/Recovery בהתאם ליצרן ולדגם. במכשירי UEFI בדוק גם Secure Boot ו־TPM אם נדרש.'],['התקן ובדוק דרייברים','בצע התקנה, התחבר לרשת, התקן עדכונים ודרייברים מהיצרן ובדוק שמע, רשת, גרפיקה וטעינה.']];if(g.issue.includes('לא נדלק'))return [['בדוק מקור מתח','נסה שקע, מטען וכבל ידועים כתקינים. השאר בטעינה 20–30 דקות אם מדובר במכשיר עם סוללה.'],['בצע הפעלה מאולצת','נסה את צירוף המקשים הרשמי של היצרן להפעלה/איפוס כפוי בלי למחוק נתונים.'],['הסר אביזרים','נתק USB, כרטיסי זיכרון, תחנות עגינה וציוד חיצוני.'],['בדוק סימני חיים','חפש LED, רטט, מאוורר, צליל, חום חריג או זיהוי במחשב — אלה עוזרים להבדיל בין מסך, מתח ולוח.'],['עצור אם יש סכנה','אם יש ריח שרוף, נפיחות בסוללה או חום קיצוני — אל תחבר שוב לחשמל ופנה לטכנאי.']];return common}
function openGuide(i){const g=(window.lastMatches||[])[i];if(!g)return;const steps=stepsFor(g);article.innerHTML=`<h1>${g.title}</h1><div class="sub">${g.cat} / ${g.brand} / ${g.series} / ${g.year}<br>מטרת המדריך: לאבחן ולטפל בבעיה “${g.issue}” תוך צמצום סיכון לנתונים ולחומרה.</div><div class="warning"><b>לפני שמתחילים:</b> נתק מתח לפני פירוק. אל תפתח ספקי כוח, טלוויזיות או ציוד במתח גבוה ללא הכשרה. סוללה נפוחה או פגועה אינה מיועדת לתיקון ביתי.</div><div class="steps">${steps.map(s=>`<div class="step"><b>${s[0]}</b>${s[1]}</div>`).join('')}</div>`;guideAside.innerHTML=`<div class="asidecard"><h4>פרטי המדריך</h4><ul><li>רמה: ${g.diff}</li><li>זמן: ${guideTime(g.diff)}</li><li>שנת דגם: ${g.year}</li><li>יצרן: ${g.brand}</li></ul></div><div class="asidecard"><h4>כלים בסיסיים</h4><ul><li>מטען/כבל תקין לבדיקה</li><li>מחשב נוסף במקרה הצורך</li><li>גיבוי נתונים</li><li>כלי פירוק רק אם נדרש</li></ul></div><div class="asidecard"><h4>מתי לא להמשיך</h4><ul><li>סוללה נפוחה</li><li>ריח שרוף</li><li>מתח גבוה חשוף</li><li>נזק נוזלים פעיל</li></ul></div>`;modal.classList.add('open');document.body.style.overflow='hidden'}
function closeGuide(){modal.classList.remove('open');document.body.style.overflow=''}
function quick(v){q.value=v;searchGuides();guides.scrollIntoView({behavior:'smooth'})}function focusSearch(){q.focus()}q.addEventListener('keydown',e=>{if(e.key==='Enter')searchGuides()});
renderSide();renderCats();window.lastMatches=fallbackMatches('', '', '');renderResults();
