const form=document.getElementById('searchForm');
const q=document.getElementById('q');
const clearBtn=document.getElementById('clearBtn');
const suggestions=document.getElementById('suggestions');
const resultsSection=document.getElementById('resultsSection');
const results=document.getElementById('results');
const resultTitle=document.getElementById('resultTitle');
const resultMeta=document.getElementById('resultMeta');
const sourceTabs=document.getElementById('sourceTabs');
const guideModal=document.getElementById('guideModal');
const guideBody=document.getElementById('guideBody');
const guideSource=document.getElementById('guideSource');

let allResults=[];let activeSource='all';let suggestTimer=null;let suggestIndex=-1;let lastSuggestItems=[];let requestToken=0;
const common=['iPhone battery replacement','Samsung Galaxy screen replacement','PlayStation 5 HDMI repair','MacBook not charging','Nintendo Switch joy-con repair','Dell XPS battery replacement','Pixel screen replacement','iPad charging port repair','Windows laptop fan noise','Xbox Series X no display','motherboard no power','USB device not recognized'];
const related={
  'not charging':['charging port','battery','power IC','USB-C','Lightning','charger','cable'],
  'no display':['HDMI','black screen','display output','screen','video IC','no signal'],
  'battery':['battery replacement','battery health','not charging','swollen battery','battery drain'],
  'screen':['screen replacement','black screen','display','touchscreen','flicker','no image'],
  'motherboard':['logic board','mainboard','PCB','boardview','schematic','no power'],
  'wifi':['wireless','network','Wi-Fi','antenna','adapter','no internet']
};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function api(payload){const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'Search service unavailable');return data;}
function setClear(){clearBtn.classList.toggle('visible',!!q.value);}function closeSuggestions(){suggestions.classList.remove('open');suggestIndex=-1;}function iconFor(item){if(item.source==='ifixit')return '↗';if(item.source==='repairai')return '⌘';if(item.source==='tools')return '⌁';return '⌕';}
function localRelated(value){const n=value.toLowerCase();const extra=[];for(const [k,vals] of Object.entries(related)){if(n.includes(k)||k.includes(n))for(const v of vals)extra.push(`${value} ${v}`);}return extra;}
function renderSuggestions(items){lastSuggestItems=items;suggestIndex=-1;if(!items.length){closeSuggestions();return;}suggestions.innerHTML=items.map((x,i)=>`<button type="button" class="suggestion-row" data-i="${i}" role="option"><span class="suggestion-icon">${iconFor(x)}</span><span class="suggestion-copy"><b>${esc(x.text)}</b>${x.hint?`<small>${esc(x.hint)}</small>`:''}</span><span class="suggestion-source">${esc(x.sourceLabel||'')}</span></button>`).join('')+`<div class="suggestion-footer">Related terms + live repair indexes · no AI</div>`;suggestions.classList.add('open');suggestions.querySelectorAll('.suggestion-row').forEach((b,i)=>b.onclick=()=>chooseSuggestion(i));}
function chooseSuggestion(i){const item=lastSuggestItems[i];if(!item)return;q.value=item.text;setClear();closeSuggestions();performSearch();}
async function loadSuggestions(){const value=q.value.trim();setClear();if(value.length<2){const v=value.toLowerCase();renderSuggestions(common.filter(x=>!v||x.toLowerCase().includes(v)).slice(0,8).map(text=>({text,hint:'Popular repair search',source:'local',sourceLabel:'Popular'})));return;}const token=++requestToken;const local=[...common.filter(x=>x.toLowerCase().includes(value.toLowerCase())),...localRelated(value)].slice(0,6).map(text=>({text,hint:'Related repair',source:'local',sourceLabel:'Related'}));try{const data=await api({mode:'suggest',query:value});if(token!==requestToken)return;const remote=Array.isArray(data.suggestions)?data.suggestions:[];const seen=new Set();const items=[...remote,...local].filter(x=>{const k=x.text.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}).slice(0,9);renderSuggestions(items);}catch{if(token===requestToken)renderSuggestions(local.length?local:common.slice(0,7).map(text=>({text,source:'local',sourceLabel:'Popular'})));}}
q.addEventListener('input',()=>{clearTimeout(suggestTimer);suggestTimer=setTimeout(loadSuggestions,170);});q.addEventListener('focus',loadSuggestions);q.addEventListener('keydown',e=>{if(!suggestions.classList.contains('open'))return;if(e.key==='ArrowDown'){e.preventDefault();suggestIndex=Math.min(suggestIndex+1,lastSuggestItems.length-1);paintSuggestSelection();}if(e.key==='ArrowUp'){e.preventDefault();suggestIndex=Math.max(suggestIndex-1,0);paintSuggestSelection();}if(e.key==='Enter'&&suggestIndex>=0){e.preventDefault();chooseSuggestion(suggestIndex);}if(e.key==='Escape')closeSuggestions();});
function paintSuggestSelection(){suggestions.querySelectorAll('.suggestion-row').forEach((el,i)=>el.classList.toggle('active',i===suggestIndex));}document.addEventListener('click',e=>{if(!e.target.closest('.google-search'))closeSuggestions();});clearBtn.onclick=()=>{q.value='';setClear();q.focus();loadSuggestions();};form.addEventListener('submit',e=>{e.preventDefault();closeSuggestions();performSearch();});document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{q.value=b.dataset.query;setClear();performSearch();}));sourceTabs.addEventListener('click',e=>{const b=e.target.closest('button[data-source]');if(!b)return;activeSource=b.dataset.source;sourceTabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderResults();});
async function performSearch(){const query=q.value.trim();if(!query){q.focus();loadSuggestions();return;}history.replaceState(null,'',`?q=${encodeURIComponent(query)}`);resultsSection.hidden=false;resultTitle.textContent=`Results for “${query}”`;resultMeta.textContent='Searching connected repair libraries…';results.innerHTML='<div class="loading-card"><div class="loading-line"><span class="spinner"></span><span>Building your repair result set…</span></div></div>';resultsSection.scrollIntoView({behavior:'smooth',block:'start'});const token=++requestToken;try{const data=await api({mode:'search',query});if(token!==requestToken)return;allResults=Array.isArray(data.results)?data.results:[];const filtered=data.lowQualityFiltered?` · ${data.lowQualityFiltered} weak guides hidden`:'';resultMeta.textContent=`${allResults.length} indexed matches · ${data.sourcesUsed||0} connected libraries${filtered}`;renderResults();}catch(err){if(token!==requestToken)return;allResults=[];resultMeta.textContent='Search failed';results.innerHTML=`<div class="error-card"><b>Couldn’t search the repair indexes.</b><div>${esc(err.message)}</div></div>`;}}
function renderResults(){const items=activeSource==='all'?allResults:allResults.filter(x=>x.source===activeSource);if(!items.length){results.innerHTML='<div class="empty-card">No strong matches here. Try a device family plus a symptom, for example “PS5 no display” or “iPhone 15 battery”.</div>';return;}results.innerHTML=items.map((item,i)=>{const img=item.image?`<img src="${esc(item.image)}" alt="" loading="lazy">`:esc((item.sourceLabel||'FX').slice(0,2).toUpperCase());const quality=item.quality&&item.openMode==='guide'?`<span class="quality-pill ${esc(item.quality)}">${item.quality==='full'?'Full guide':'Basic guide'}${item.stepCount?` · ${item.stepCount} steps`:''}</span>`:'';return `<article class="result-card" data-key="${esc(item.key||String(i))}"><div class="result-thumb">${img}</div><div class="result-main"><h3>${esc(item.title)}</h3><p>${esc(item.subtitle||item.summary||'')}</p><div class="result-meta"><span class="source-pill ${esc(item.source)}">${esc(item.sourceLabel||item.source)}</span>${quality}${item.category?`<span>${esc(item.category)}</span>`:''}${item.type?`<span>· ${esc(item.type)}</span>`:''}</div></div><button class="result-action">Open in FixBase →</button></article>`;}).join('');results.querySelectorAll('.result-card').forEach(card=>card.addEventListener('click',()=>{const item=items.find(x=>String(x.key)===card.dataset.key);if(item)openResult(item);}));}
async function openResult(item){openModal();guideSource.innerHTML=`<span class="source-pill ${esc(item.source)}">${esc(item.sourceLabel||item.source)}</span><span class="internal-pill">Opened inside FixBase</span>`;guideBody.innerHTML='<div class="loading-card"><div class="loading-line"><span class="spinner"></span><span>Loading into FixBase…</span></div></div>';if(item.openMode==='guide'&&item.guideId){try{const data=await api({mode:'guide',guideId:item.guideId});renderGuide(data);}catch(err){guideBody.innerHTML=`<div class="error-card">${esc(err.message)}</div>`;}return;}if(item.openMode==='community'&&item.path){try{const data=await api({mode:'community',path:item.path});renderCommunity(data);}catch(err){guideBody.innerHTML=`<div class="error-card">${esc(err.message)}</div>`;}return;}renderReference(item);}
function openModal(){guideModal.classList.add('open');guideModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}function closeModal(){guideModal.classList.remove('open');guideModal.setAttribute('aria-hidden','true');document.body.style.overflow='';}document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
function renderReference(item){const hints=[];const t=`${item.title||''} ${item.subtitle||''}`.toLowerCase();if(t.includes('board')||t.includes('schematic')||t.includes('pcb'))hints.push('Use this reference for board-level diagnosis, measurements, boardview or schematic context.');if(t.includes('device'))hints.push('Use this device entry as a starting point, then search the exact fault or repair action.');guideBody.innerHTML=`<div class="reference-hero"><span class="reference-label">INTERNAL REFERENCE</span><h1 id="guideTitle">${esc(item.title||'Repair reference')}</h1><p>${esc(item.subtitle||'This source is indexed by FixBase as supporting repair knowledge.')}</p></div><div class="reference-grid"><div class="info-box"><b>Source</b><p>${esc(item.sourceLabel||item.source||'Open repair source')}</p></div><div class="info-box"><b>Type</b><p>${esc(item.type||'Reference')}</p></div><div class="info-box"><b>Category</b><p>${esc(item.category||'Repair knowledge')}</p></div></div>${hints.map(x=>`<div class="reference-tip">${esc(x)}</div>`).join('')}<div class="source-note">This entry is displayed inside FixBase. Source attribution is preserved, but FixBase does not automatically send you to another site.</div>`;}
function renderGuide(g){const tools=(g.tools||[]).map(x=>`<li>${esc(x)}</li>`).join('');const parts=(g.parts||[]).map(x=>`<li>${esc(x)}</li>`).join('');const qualityNote=g.quality==='reference'?`<div class="guide-quality-warning"><b>This source is only a reference, not a complete repair guide.</b><p>FixBase did not find enough usable step-by-step content, so it is not presented as a full guide.</p></div>`:'';const steps=(g.steps||[]).map((s,i)=>{const notes=(s.notes||[]).map(n=>`<div class="step-note">Note: ${esc(n)}</div>`).join('');const warnings=(s.warnings||[]).map(w=>`<div class="step-warning">Warning: ${esc(w)}</div>`).join('');const lines=(s.lines||[]).map(line=>`<p>${esc(line)}</p>`).join('');return `<section class="guide-step"><span class="step-num">${i+1}</span><div><h3>${esc(s.title||`Step ${i+1}`)}</h3>${warnings}${lines}${notes}${s.image?`<img class="guide-image" src="${esc(s.image)}" alt="Step ${i+1}" loading="lazy">`:''}</div></section>`;}).join('');guideBody.innerHTML=`<h1 id="guideTitle">${esc(g.title||'Repair guide')}</h1>${g.difficulty||g.time?`<div class="guide-facts">${g.difficulty?`<span>Difficulty: <b>${esc(g.difficulty)}</b></span>`:''}${g.time?`<span>Time: <b>${esc(g.time)}</b></span>`:''}</div>`:''}<p class="intro">${esc(g.introduction||'')}</p>${qualityNote}${(tools||parts)?`<div class="guide-summary-grid">${tools?`<div class="info-box"><b>Tools</b><ul>${tools}</ul></div>`:''}${parts?`<div class="info-box"><b>Parts</b><ul>${parts}</ul></div>`:''}</div>`:''}${steps||'<div class="guide-quality-warning"><b>No usable steps were found in this source.</b></div>'}<div class="source-note">Guide content is shown inside FixBase with source attribution.</div>`;}
function renderCommunity(d){guideBody.innerHTML=`<h1 id="guideTitle">${esc(d.title||'Community repair document')}</h1><p class="intro">Community repair documentation rendered directly inside FixBase.</p><div class="community-markdown">${(d.lines||[]).map(line=>line.startsWith('# ')?`<h2>${esc(line.slice(2))}</h2>`:line.startsWith('## ')?`<h3>${esc(line.slice(3))}</h3>`:line.startsWith('- ')?`<p>• ${esc(line.slice(2))}</p>`:line.trim()?`<p>${esc(line)}</p>`:'').join('')}</div><div class="source-note">Source attribution preserved. Document displayed inside FixBase.</div>`;}
const initial=new URLSearchParams(location.search).get('q');if(initial){q.value=initial;setClear();performSearch();}
