const form=document.getElementById('searchForm');
const q=document.getElementById('q');
const clearBtn=document.getElementById('clearBtn');
const suggestions=document.getElementById('suggestions');
const resultsSection=document.getElementById('resultsSection');
const results=document.getElementById('results');
const resultTitle=document.getElementById('resultTitle');
const resultMeta=document.getElementById('resultMeta');
const relatedRow=document.getElementById('relatedRow');
const guideModal=document.getElementById('guideModal');
const guideBody=document.getElementById('guideBody');
const guideSource=document.getElementById('guideSource');
const filterButtons=[...document.querySelectorAll('.filters button[data-source]')];
let allResults=[];let activeSource='all';let suggestTimer=null;let suggestIndex=-1;let lastSuggestItems=[];let requestToken=0;
const common=['iPhone battery replacement','iPhone not charging','Samsung boot loop','PlayStation 5 no display','PS5 HDMI repair','MacBook battery replacement','Nintendo Switch charging port','Dell laptop overheating','Pixel screen replacement','Xbox no signal','router no internet','SSD not detected'];
const relatedMap={charging:['not charging','charging port','battery','USB-C','power issue'],display:['no display','black screen','HDMI','screen replacement','backlight'],battery:['battery replacement','battery drain','swollen battery','not charging'],boot:['boot loop','won’t turn on','recovery mode','firmware','startup issue'],heat:['overheating','fan','thermal paste','cooling','shutdown'],wifi:['Wi-Fi','network','antenna','no internet','wireless']};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
async function api(payload){const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'Search service unavailable');return data;}
function setClear(){clearBtn.classList.toggle('visible',!!q.value);}function closeSuggestions(){suggestions.classList.remove('open');suggestIndex=-1;}
function iconFor(item){if(item.source==='ifixit')return '↗';if(item.source==='repairai')return '⌘';if(item.source==='tools')return '⌁';return '⌕';}
function renderSuggestions(items){lastSuggestItems=items;suggestIndex=-1;if(!items.length){closeSuggestions();return;}suggestions.innerHTML=items.map((x,i)=>`<button type="button" class="suggestion-row" data-i="${i}"><span class="suggestion-icon">${iconFor(x)}</span><span class="suggestion-copy"><b>${esc(x.text)}</b>${x.hint?`<small>${esc(x.hint)}</small>`:''}</span><span class="suggestion-source">${esc(x.sourceLabel||'')}</span></button>`).join('')+`<div class="suggestion-footer">Related terms and partial matches are included. No AI.</div>`;suggestions.classList.add('open');suggestions.querySelectorAll('.suggestion-row').forEach((b,i)=>b.onclick=()=>chooseSuggestion(i));}
function chooseSuggestion(i){const item=lastSuggestItems[i];if(!item)return;q.value=item.text;setClear();closeSuggestions();performSearch();}
async function loadSuggestions(){const value=q.value.trim();setClear();if(value.length<2){const v=value.toLowerCase();renderSuggestions(common.filter(x=>!v||x.toLowerCase().includes(v)).slice(0,8).map(text=>({text,hint:'Popular repair search',source:'local',sourceLabel:'Popular'})));return;}const token=++requestToken;try{const data=await api({mode:'suggest',query:value});if(token!==requestToken)return;const remote=Array.isArray(data.suggestions)?data.suggestions:[];const local=common.filter(x=>x.toLowerCase().includes(value.toLowerCase())).map(text=>({text,hint:'Related repair',source:'local',sourceLabel:'Related'}));const seen=new Set();renderSuggestions([...remote,...local].filter(x=>{const k=x.text.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).slice(0,9));}catch{if(token===requestToken)renderSuggestions(common.filter(x=>x.toLowerCase().includes(value.toLowerCase())).slice(0,8).map(text=>({text,source:'local',sourceLabel:'Related'})));}}
q.addEventListener('input',()=>{clearTimeout(suggestTimer);suggestTimer=setTimeout(loadSuggestions,160);});q.addEventListener('focus',loadSuggestions);q.addEventListener('keydown',e=>{if(!suggestions.classList.contains('open'))return;if(e.key==='ArrowDown'){e.preventDefault();suggestIndex=Math.min(suggestIndex+1,lastSuggestItems.length-1);paintSuggestSelection();}if(e.key==='ArrowUp'){e.preventDefault();suggestIndex=Math.max(suggestIndex-1,0);paintSuggestSelection();}if(e.key==='Enter'&&suggestIndex>=0){e.preventDefault();chooseSuggestion(suggestIndex);}if(e.key==='Escape')closeSuggestions();});
function paintSuggestSelection(){suggestions.querySelectorAll('.suggestion-row').forEach((el,i)=>el.classList.toggle('active',i===suggestIndex));}
document.addEventListener('click',e=>{if(!e.target.closest('.google-search'))closeSuggestions();});clearBtn.onclick=()=>{q.value='';setClear();q.focus();loadSuggestions();};form.addEventListener('submit',e=>{e.preventDefault();closeSuggestions();performSearch();});document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{q.value=b.dataset.query;setClear();performSearch();}));
filterButtons.forEach(b=>b.addEventListener('click',()=>{activeSource=b.dataset.source;filterButtons.forEach(x=>x.classList.toggle('active',x===b));renderResults();}));
function renderRelated(query){const t=query.toLowerCase();let terms=[];for(const [key,vals] of Object.entries(relatedMap))if(t.includes(key)||vals.some(v=>t.includes(v.toLowerCase())))terms.push(...vals);terms=[...new Set(terms)].filter(x=>!t.includes(x.toLowerCase())).slice(0,6);relatedRow.innerHTML=terms.map(x=>`<button data-related="${esc(x)}">${esc(x)}</button>`).join('');relatedRow.querySelectorAll('button').forEach(b=>b.onclick=()=>{q.value=`${query} ${b.dataset.related}`;setClear();performSearch();});}
async function performSearch(){const query=q.value.trim();if(!query){q.focus();loadSuggestions();return;}history.replaceState(null,'',`?q=${encodeURIComponent(query)}`);resultsSection.hidden=false;resultTitle.textContent=`Results for “${query}”`;resultMeta.textContent='Searching repair knowledge…';renderRelated(query);results.innerHTML='<div class="loading-card">Searching guides, devices and repair references…</div>';resultsSection.scrollIntoView({behavior:'smooth',block:'start'});const token=++requestToken;try{const data=await api({mode:'search',query});if(token!==requestToken)return;allResults=Array.isArray(data.results)?data.results:[];const filtered=data.lowQualityFiltered?` · ${data.lowQualityFiltered} weak guides hidden`:'';resultMeta.textContent=`${allResults.length} matches from ${data.sourcesUsed||0} knowledge sources${filtered}`;renderResults();}catch(err){if(token!==requestToken)return;allResults=[];resultMeta.textContent='Search failed';results.innerHTML=`<div class="error-card"><b>Search failed.</b><div>${esc(err.message)}</div></div>`;}}
function renderResults(){const items=activeSource==='all'?allResults:allResults.filter(x=>x.source===activeSource);if(!items.length){results.innerHTML='<div class="empty-card">No strong matches here. Try fewer words, a model family, or a related symptom.</div>';return;}results.innerHTML=items.map((item,i)=>{const img=item.image?`<img src="${esc(item.image)}" alt="" loading="lazy">`:esc((item.sourceLabel||'FX').slice(0,2).toUpperCase());const quality=item.quality&&item.openMode==='guide'?`<span class="quality-pill">${item.quality==='full'?'Full guide':'Basic guide'}${item.stepCount?` · ${item.stepCount} steps`:''}</span>`:'';return `<article class="result-card" data-i="${i}"><div class="result-thumb">${img}</div><div class="result-main"><h3>${esc(item.title)}</h3><p>${esc(item.subtitle||item.summary||'')}</p><div class="result-meta"><span class="source-pill ${esc(item.source)}">${esc(item.sourceLabel||item.source)}</span>${quality}${item.category?`<span>${esc(item.category)}</span>`:''}${item.type?`<span>· ${esc(item.type)}</span>`:''}</div></div><button class="result-action" type="button">Open in FixBase →</button></article>`;}).join('');results.querySelectorAll('.result-card').forEach((card,i)=>card.onclick=()=>openResult(items[i]));}
async function openResult(item){openModal();guideSource.innerHTML=`<span class="source-pill ${esc(item.source)}">${esc(item.sourceLabel||'FixBase source')}</span>`;guideBody.innerHTML='<div class="loading-card">Loading inside FixBase…</div>';if(item.openMode==='guide'&&item.guideId){try{return renderGuide(await api({mode:'guide',guideId:item.guideId}));}catch(err){return showInternalError(err);}}if(item.openMode==='community'&&item.path){try{return renderCommunity(await api({mode:'community',path:item.path}));}catch(err){return showInternalError(err);}}renderReference(item);}
function renderReference(item){guideBody.innerHTML=`<h1>${esc(item.title||'Repair reference')}</h1><p class="intro">${esc(item.subtitle||'This result is indexed by FixBase as a technical reference.')}</p><div class="internal-reference"><h3>Internal reference</h3><dl><dt>Source</dt><dd>${esc(item.sourceLabel||item.source||'Unknown')}</dd><dt>Type</dt><dd>${esc(item.type||'Reference')}</dd><dt>Category</dt><dd>${esc(item.category||'General repair')}</dd></dl><p>FixBase keeps this result here instead of sending you away. Structured repair content is rendered directly whenever the source exposes it.</p></div>`;}
function showInternalError(err){guideBody.innerHTML=`<div class="error-card"><b>Couldn’t load this item.</b><div>${esc(err.message||'Unknown error')}</div></div>`;}
function openModal(){guideModal.classList.add('open');guideModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}function closeModal(){guideModal.classList.remove('open');guideModal.setAttribute('aria-hidden','true');document.body.style.overflow='';}document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
function renderGuide(g){const tools=(g.tools||[]).map(x=>`<li>${esc(x)}</li>`).join('');const parts=(g.parts||[]).map(x=>`<li>${esc(x)}</li>`).join('');const steps=(g.steps||[]).map((s,i)=>`<section class="guide-step"><span class="step-num">${i+1}</span><div><h3>${esc(s.title||`Step ${i+1}`)}</h3>${(s.warnings||[]).map(w=>`<div class="step-warning">Warning: ${esc(w)}</div>`).join('')}${(s.lines||[]).map(line=>`<p>${esc(line)}</p>`).join('')}${(s.notes||[]).map(n=>`<div class="step-note">Note: ${esc(n)}</div>`).join('')}${s.image?`<img class="guide-image" src="${esc(s.image)}" alt="Step ${i+1}" loading="lazy">`:''}</div></section>`).join('');guideBody.innerHTML=`<h1>${esc(g.title||'Repair guide')}</h1><div class="guide-facts">${g.difficulty?`<span>Difficulty: <b>${esc(g.difficulty)}</b></span>`:''}${g.time?`<span>Time: <b>${esc(g.time)}</b></span>`:''}${g.quality?`<span>Guide quality: <b>${esc(g.quality)}</b></span>`:''}</div><p class="intro">${esc(g.introduction||'')}</p>${(tools||parts)?`<div class="guide-summary-grid">${tools?`<div class="info-box"><b>Tools</b><ul>${tools}</ul></div>`:''}${parts?`<div class="info-box"><b>Parts</b><ul>${parts}</ul></div>`:''}</div>`:''}${steps||'<div class="empty-card">No usable step-by-step content was available for this result.</div>'}<div class="source-note">Source attribution preserved inside FixBase.</div>`;}
function renderCommunity(d){const body=(d.lines||[]).map(line=>line.startsWith('# ')?`<h2>${esc(line.slice(2))}</h2>`:line.startsWith('## ')?`<h3>${esc(line.slice(3))}</h3>`:line.startsWith('- ')?`<p>• ${esc(line.slice(2))}</p>`:line.trim()?`<p>${esc(line)}</p>`:'').join('');guideBody.innerHTML=`<h1>${esc(d.title||'Community repair document')}</h1><p class="intro">Open community repair documentation rendered inside FixBase.</p><div class="community-markdown">${body}</div><div class="source-note">Source attribution preserved inside FixBase.</div>`;}
const initial=new URLSearchParams(location.search).get('q');if(initial){q.value=initial;setClear();performSearch();}
